### ISSUE TITLE
Add Bluetooth Capability in the App

### ISSUE THREAD

**Issue by osamasalahuddin** [shoaib333/TestProject#1]
Bluetooth ability need to be added in the app

**Comment by shoaib333** [comment]
Sub tasks
-Enable Bluetooth if disable / or enable it implicitly and then notify the user
-Search for devices
-Select a device with specific name or id
-Send push notification to the other device.

**Comment by osamasalahuddin** [comment]
Functionality added in the following Branch:
https://github.com/shoaib333/TestProject/tree/BTIntegration
- Bluetooth Enabled after asking from user
- Searching for devices
- Connects with a specific device and opens communication socket
- Sends a message to the other device

To be done:
Some minor fixes regarding some crashes
